server:
  port: 8001

mybatis:
  type-aliases-package: com.hzm.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: springcloud-provider-dept-8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver #数据源
    url: jdbc:mysql://localhost:3306/db01?serverTimezone=UTC&useUnicode=true
    username: root
    password: Lp702