server:
  port: 8001

mybatis:
  type-aliases-package: com.hzm.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: springcloud-provider-dept-8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver #数据源
    url: jdbc:mysql://localhost:3306/db01?serverTimezone=UTC&useUnicode=true
    username: root
    password: Lp702

#eureka配置  注册到注册中心
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8001

#info配置
info:
  app.name: hzm-springcloud
  company.name: blog.hzmstduy.com